### ISSUE TITLE
npx init output use npm and tuto use yarn

### ISSUE THREAD

**Issue by arnobase** [Phala-Network/phat-contract-starter-kit#11]
https://github.com/Phala-Network/phat-contract-starter-kit/blob/3ba9c422132afdf047749081fd5f5f0fb1cdeb47/README.md?plain=1#L47
when using `npx @phala/fn@latest init` cmd, the output says:
```
Downloading the template: https://github.com/Phala-Network/phat-contract-starter-kit... ✔
The project is created in /Users/arno/Code/phat/phat-test 🎉
Now run:

  cd phat-test
  npm install
```
maybe change the output to use yarn on both sides, or propose npm here

**Comment by HashWarlock** [comment]
@Leechael something to check on the `@phala/fn` side.

**Comment by Leechael** [comment]
@arnobase @HashWarlock Thanks for pointing that out!

It will updated in next release:
https://github.com/Phala-Network/phat-function-cli/pull/10
